name: proyecto_josue

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Main Code Download 
        uses: actions/checkout@v3
      - name: Environment Set-Up
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Node Version Verification
        run: node -v
      - name: Dependency instalation
        run: npm install
      #- name: Sonarscanner installation
      #  run: npm install -g sonar-scanner
      #- name: Lint test
      #  run: npm run lint
      - name: Unit test
        run: npm run test
      #- name: SonarQube scan
      #  run: npm run sonar
      - name: Build App
        run: npm run build
      - name: Upload files to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  CD:
    runs-on: self-hosted
    needs: CI
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: List files
        run: dir
      #- name: Deploy
      #  run: cp repos_ucreativa/* /var/www/josue/

