name: proyecto_josue

on: [push]

jobs:
  fase-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Main Code Download 
        uses: actions/checkout@v3
      - name: Environment Set-Up
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
      - name: Node Version Verification
        run: node -v
      - name: Dependency instalation
        run: npm run install
      - name: Lint test
        run: npm run lint
      - name: Unit test
        run: npm run test
      - name: SonarQube scan
        run: npm run sonar


